name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on:  self-hosted
    steps:
        - uses: actions/checkout@v4
        - name: Deploy locally
          run: |
            cd ~/demo-app
            git pull origin main
            docker rm -f $(docker ps -aq --filter "name=demo-app_app") 2>/dev/null || true
            docker-compose up -d --build
            docker-compose ps
